// <auto-generated />
using System;
using DispersionModeling.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DispersionModeling.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190604212858_PollutantListModified")]
    partial class PollutantListModified
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DispersionModeling.API.Models.DispersionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AirTemperature");

                    b.Property<int>("AtmosphericConditions");

                    b.Property<int>("CloudCoverage");

                    b.Property<DateTime>("CurrentDate");

                    b.Property<double>("EmissionOfPollutantsConcentration");

                    b.Property<double>("ExitTemperature");

                    b.Property<int>("SmokeExitSpeed");

                    b.Property<int>("SolarRadiations");

                    b.Property<string>("TerrainType");

                    b.Property<string>("WindDirection");

                    b.Property<int>("WindSpeedAtTenMetters");

                    b.HasKey("Id");

                    b.ToTable("DispersionModels");
                });

            modelBuilder.Entity("DispersionModeling.API.Models.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("DispersionModeling.API.Models.GPSLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Altitude");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.HasKey("Id");

                    b.ToTable("GPSLocations");
                });

            modelBuilder.Entity("DispersionModeling.API.Models.PollutantList", b =>
                {
                    b.Property<int>("PollutantListID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChemicalFormula");

                    b.Property<string>("Measure");

                    b.Property<string>("Name");

                    b.HasKey("PollutantListID");

                    b.ToTable("PollutantLists");
                });

            modelBuilder.Entity("DispersionModeling.API.Models.PollutionSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Altitude");

                    b.Property<double>("ChimneyDiameter");

                    b.Property<double>("ChimneyHeight");

                    b.Property<string>("Description");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<double>("MaxDistance");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("PollutionSources");
                });

            modelBuilder.Entity("DispersionModeling.API.Models.StationType", b =>
                {
                    b.Property<int>("StationTypeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("StationTypeID");

                    b.ToTable("StationTypes");
                });

            modelBuilder.Entity("DispersionModeling.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
